In [2]:
import torch

# load the ingredient embeddings
ingredient_embeddings = torch.load("./ingredient_embeddings_gat_v2.pt")
bert_embeddings = torch.load("./ingredient_embeddings_bert.pt")

# inspect the embeddings
print(ingredient_embeddings)
print(bert_embeddings)

tensor([[-3.5067e-02,  4.0401e-02,  6.2585e-02,  ...,  8.7442e-02,
         -3.4544e-02,  2.6393e-02],
        [ 2.8923e-03,  3.5581e-02,  4.6746e-02,  ...,  6.9635e-02,
         -3.1150e-02, -2.4894e-03],
        [-3.8004e-02,  5.1686e-02,  1.3883e-01,  ...,  1.2125e-01,
         -1.7026e-02,  8.5565e-03],
        ...,
        [ 2.5114e+00, -5.5451e-02, -4.2354e-01,  ...,  3.6905e-02,
          1.6226e+00,  7.9568e-01],
        [-2.0718e-02, -1.0674e+00,  1.5850e+00,  ...,  1.0442e+00,
          1.6812e+00,  8.0268e-01],
        [ 2.1651e-01,  4.2835e-01, -1.3640e+00,  ...,  6.5846e-02,
          1.0917e+00, -3.6186e-01]])
tensor([[-0.7719,  0.4169, -0.7402,  ...,  0.2603,  0.3389,  0.4507],
        [-0.3830, -0.0660, -0.2323,  ..., -0.1751,  0.4549,  0.2395],
        [-0.4955,  0.4092, -1.1320,  ..., -0.4718, -0.1319,  0.4905],
        ...,
        [-0.4084, -0.0712, -0.4128,  ..., -0.2269, -0.0887,  0.3565],
        [-0.8203,  0.4091, -0.4271,  ..., -0.3878,  0.0322,  0.7871],
     

/tmp/ipykernel_928587/1702126324.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ingredient_embeddings = torch.load("./ingredient_embeddings_gat_v2.pt")
/tmp/ipykernel_9

In [ ]:
# print out the top 10 paired ingredients in bert with the highest cosine similarity
# bert
import pandas as pd
ing_id = "./utils/data/test_labels_ingr_id.csv"

df = pd.read_csv(ing_id)
ingr_name = df.columns[1:-1].to_list()

cos = torch.nn.CosineSimilarity(dim=0)

sim_dict = {}

for i in range(10):
    for j in range(i+1, len(bert_embeddings)):
        sim = cos(bert_embeddings[i], bert_embeddings[j])
        sim_dict[(ingr_name[i], ingr_name[j])] = sim.item()
        
sorted_sim_dict = sorted(sim_dict.items(), key=lambda x: x[1], reverse=True)

for i in range(100):
    print(sorted_sim_dict[i])


(('quinoa', 'jicama'), 0.9840413331985474)
(('berries', 'corn'), 0.9838709831237793)
(('berries', 'grapes'), 0.9820185899734497)
(('berries', 'wine'), 0.9818021655082703)
(('carrot', 'wine'), 0.9810669422149658)
(('berries', 'sugar'), 0.9809611439704895)
(('berries', 'milk'), 0.980205237865448)
(('berries', 'tuna'), 0.979519784450531)
(('brown rice', 'white rice'), 0.978987991809845)
(('berries', 'squash'), 0.9789713025093079)
(('berries', 'garlic'), 0.9780934453010559)
(('berries', 'chicken'), 0.977954089641571)
(('carrot', 'chicken'), 0.9777261018753052)
(('carrot', 'tuna'), 0.9777044057846069)
(('berries', 'butter'), 0.9775931239128113)
(('carrot', 'ginger'), 0.9765673279762268)
(('berries', 'orange'), 0.9763238430023193)
(('berries', 'syrup'), 0.975771963596344)
(('quinoa', 'pesto'), 0.9757385849952698)
(('berries', 'chili'), 0.9755913615226746)
(('berries', 'pizza'), 0.9741999506950378)
(('carrot', 'pizza'), 0.9735509157180786)
(('carrot', 'tofu'), 0.9734382629394531)
(('berries',

In [10]:
import torch

torch.load("./ingredient_graph_v2.pt", weights_only=False)

Data(x=[199, 199], edge_index=[2, 6090], edge_attr=[6090])

In [ ]:

# normalize the embeddings
ingredient_embeddings = torch.nn.functional.normalize(ingredient_embeddings, p=2, dim=1)
bert_embeddings = torch.nn.functional.normalize(bert_embeddings, p=2, dim=1)

print(ingredient_embeddings)
print(bert_embeddings)

tensor([[-0.0543,  0.0626,  0.0970,  ...,  0.1355, -0.0535,  0.0409],
        [ 0.0049,  0.0597,  0.0785,  ...,  0.1169, -0.0523, -0.0042],
        [-0.0375,  0.0510,  0.1369,  ...,  0.1196, -0.0168,  0.0084],
        ...,
        [ 0.1604, -0.0035, -0.0270,  ...,  0.0024,  0.1036,  0.0508],
        [-0.0015, -0.0779,  0.1157,  ...,  0.0762,  0.1227,  0.0586],
        [ 0.0102,  0.0201, -0.0642,  ...,  0.0031,  0.0513, -0.0170]])
tensor([[-0.0526,  0.0284, -0.0505,  ...,  0.0177,  0.0231,  0.0307],
        [-0.0265, -0.0046, -0.0161,  ..., -0.0121,  0.0315,  0.0166],
        [-0.0294,  0.0243, -0.0671,  ..., -0.0280, -0.0078,  0.0291],
        ...,
        [-0.0270, -0.0047, -0.0273,  ..., -0.0150, -0.0059,  0.0236],
        [-0.0520,  0.0259, -0.0271,  ..., -0.0246,  0.0020,  0.0499],
        [-0.0133,  0.0156,  0.0012,  ..., -0.0158,  0.0235,  0.0100]])


In [ ]:

# concatenate the embeddings
concat_embeddings = torch.cat([ingredient_embeddings, bert_embeddings], dim=1)

# Save the concatenated embeddings
# torch.save(concat_embeddings, "./ingredient_embeddings_concat.pt")